### Numpy - Array Processing

### Task 1
Write a program to create a numpy array with students names ['Reem', 'Sara', 'Maha', 'Lama', 'Waad', 'Eman', 'Noha', 'Haya', 'Renad', 'Mona'] and then sort the students’ names and spilt it into two groups each group has 5 students.

Sample Output:
```
group 1: ['Eman' 'Haya' 'Lama' 'Maha' 'Mona']
group 2: ['Noha' 'Reem' 'Renad' 'Sara' 'Waad']


In [2]:
import numpy as np

students = np.array(['Reem', 'Sara', 'Maha', 'Lama', 'Waad', 
                     'Eman', 'Noha', 'Haya', 'Renad', 'Mona'])

students_sorted = np.sort(students)
group1, group2 = np.split(students_sorted, 2)
print("group 1:", group1)
print("group 2:", group2)

group 1: ['Eman' 'Haya' 'Lama' 'Maha' 'Mona']
group 2: ['Noha' 'Reem' 'Renad' 'Sara' 'Waad']


### Task 2
Create two numpy arrays as follows:  
- students names array: ['Reem', 'Sara', 'Maha', 'Lama', 'Waad', 'Eman', 'Noha', 'Haya', 'Renad', 'Mona']  
- students grades array: [95, 99, 88, 89, 87, 90, 89, 90, 87, 88]

Then write program to print the following:
- students’ names who got above 90 in the homework.
- Highest grade
- Lowest grade
- Randomly pick a student name to solve the homework.
  
You should create two arrays:  
Array 1: students’ names  
Array 2: to hold the students' grades.

Sample Output:
```
A+ students are:
['Sara' 'Reem']
highest grade:  99
lowest grade:  87
Sara will solve the homework
```

In [3]:
import numpy as np
import random

students = np.array(['Reem', 'Sara', 'Maha', 'Lama', 'Waad',
                     'Eman', 'Noha', 'Haya', 'Renad', 'Mona'])
grades = np.array([95, 99, 88, 89, 87, 90, 89, 90, 87, 88])

A_plus_students = students[grades > 90]

highest_grade = np.max(grades)
lowest_grade = np.min(grades)
random_student = random.choice(students)

print("A+ students are:")
print(A_plus_students)
print("highest grade:", highest_grade)
print("lowest grade:", lowest_grade)
print(random_student, "will solve the homework")


A+ students are:
['Reem' 'Sara']
highest grade: 99
lowest grade: 87
Maha will solve the homework


### Task 3
Write a program that calculate and classify the rainfall average for 4 weeks.
1. Firstly, create 2D array (4,7)  to store the rainfall rates for each day in the 4 weeks.

week#1 |  9 8 6 9 7 6 8  
week#2 | 2 1 2 3 2 3 5  
week#3 | 3 5 5 7 3 2 6  
week#4 | 4 3 5 6 7 3 2  


2. Calculate the rainfall average for each week (i.e. for each row), and print the classification for that week: High, Medium or Low; based on the average as follows: 

| Rainfall average | Classification |
|------------------|----------------|
| average >= 6     |High            |
|6 > average > 3   |Medium          |
|average < = 3     |Low             |



Sample Output:
```
Classification for each week: 

Week  1 :
High : 7.57

Week  2 :
Low : 2.57

Week  3 :
Medium : 4.43

Week  4 :
Medium : 4.29

In [10]:
import numpy as np

rainfall = np.array([
    [9, 8, 6, 9, 7, 6, 8],
    [2, 1, 2, 3, 2, 3, 5],
    [3, 5, 5, 7, 3, 2, 6],
    [4, 3, 5, 6, 7, 3, 2]
])

weekly_avg = np.mean(rainfall, axis=1)
print("Classification for each week:\n")
for i in range(len(weekly_avg)):
    avg = weekly_avg[i]
    if avg >= 6:
        classification = "High"
    elif avg > 3:
        classification = "Medium"
    else:
        classification = "Low"
    
    print(f"Week {i+1}:")
    print(f"{classification} : {avg:.2f}\n")


Classification for each week:

Week 1:
High : 7.57

Week 2:
Low : 2.57

Week 3:
Medium : 4.43

Week 4:
Medium : 4.29



### Task 4
Write a program to remove the negative values in a NumPy array with 0.

Sample Output:
```
Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]

In [16]:
import numpy as np

arr = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("The original array:")
print(arr)

for i in range(len(arr)):
    if arr[i] < 0:
        arr[i] = 0
print("Replace the negative values of the said array with 0:")
print(arr)


The original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]


### Task 5
Create 2D (4,4) array with random numbers from 0 to 100 and perform the following:
1. Print the array data type.
2.	Make copy of the array, sort the copy and check if array owns its data.
3.	Print all even index array elements (index , value)
4.	Convert the array into a 1D array.
5.	Find the highest 5 values in 1D array.
6.	Convert the array to text array.


Sample Output:

Task 5.1
```
[[41 33 92 17]
[65 79 42 80]
[71 30 71 59]
[23 47  4 90]]
Array Data Type is  int64
```

Task 5.2
```
 Copy Array : 
 [[17 33 41 92]
 [42 65 79 80]
 [30 59 71 71]
 [ 4 23 47 90]] 
 base for copy array: None
```

Task 5.3
```
(0, 0) 41
(0, 2) 92
(2, 0) 71
(2, 2) 71
```

Task 5.4:
`[41 33 92 17 65 79 42 80 71 30 71 59 23 47  4 90]`

Task 5.5:
`[71 79 80 90 92]`

Task 5.6:
`['41' '33' '92' '17' '65' '79' '42' '80' '71' '30' '71' '59' '23' '47' '4'
 '90']`

In [8]:
import numpy as np

arr = np.random.randint(0, 101, (4, 4))
print("Task 5.1\n")
print(arr)
print("Array Data Type is", arr.dtype)
print("\nTask 5.2\n")
copy_arr = arr.copy()
copy_arr.sort()

print("Copy Array:\n", copy_arr)
print("base for copy array:", copy_arr.base)

print("\nTask 5.3\n")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i % 2 == 0 and j % 2 == 0:
            print((i, j), arr[i, j])

arr_1d = arr.reshape(-1)
print("\nTask 5.4:", arr_1d)

highest_5 = np.sort(arr_1d)[-5:]
print("\nTask 5.5:", highest_5)

text_arr = arr_1d.astype(str)
print("\nTask 5.6:", text_arr)



Task 5.1

[[12 52  0  6]
 [47 65  4 81]
 [19 86 70 49]
 [43 95 56 38]]
Array Data Type is int64

Task 5.2

Copy Array:
 [[ 0  6 12 52]
 [ 4 47 65 81]
 [19 49 70 86]
 [38 43 56 95]]
base for copy array: None

Task 5.3

(0, 0) 12
(0, 2) 0
(2, 0) 19
(2, 2) 70

Task 5.4: [12 52  0  6 47 65  4 81 19 86 70 49 43 95 56 38]

Task 5.5: [65 70 81 86 95]

Task 5.6: ['12' '52' '0' '6' '47' '65' '4' '81' '19' '86' '70' '49' '43' '95' '56'
 '38']
